excluded:
  - Pods

disabled_rules:
  - legacy_constructor

type_body_length:
  warning: 500
  error: 800

function_body_length:
  warning: 100
  error: 200

line_length:
  warning: 500
  error: 800

file_length:
  warning: 500
  error: 800
